### ISSUE TITLE
newtab page shouldn't steal focus from URL bar

### ISSUE THREAD

**Issue by Manishearth** [bwinton/whimsy#158] opened 2017-08-07 08:18 UTC
Even with the improved newtab page disabled, Ctrl-T gives me a tab with focus on the DuckDuckGo search.

I like DDG, but typing in the DDG search doesn't give me URL suggestions, which is what I usually do on Ctrl-T. Can we have the ability to disable the newtab page completely or remove focus from the searchbox?

**Comment by bwinton** [comment] 2017-08-08 15:15
Which OS/Version of Firefox?  I only ever get the urlbar focused when I open a new tab…

**Comment by Manishearth** [comment] 2017-08-08 15:15
Nightly, OSX

**Comment by Manishearth** [comment] 2017-08-08 15:21
Nightly, OSX.

This seems fixed now.

**Comment by Manishearth** [comment] 2017-08-08 15:30
Or, no, it's happening again. If my cursor is already on the URL bar it works fine, but if it's e.g. typing in a github issue, and I Ctrl-T, the cursor moves to the DDG bar instead of the URL bar.

**Comment by strugee** [comment] 2017-08-08 17:22
I can also reproduce this. Cmd-L also does not work, which makes this doubly-painful.

**Comment by bwinton** [comment] 2017-08-08 17:27
Hmm.  I still can't reproduce either of these behaviours on today's Nightly (57.0a1, 2017-08-08 64-bit) on macOS 10.12.6.  Is there anything in the Browser Console, and can you reproduce them in a new, clean profile?

**Comment by strugee** [comment] 2017-08-15 20:00
I'm on the 2017-08-11 Nightly and I see different behavior now... looks like _neither_ the search box nor the URL bar are focused now?

**Comment by bwinton** [comment] 2017-08-15 20:05
At this point, I'm convinced it's a Firefox bug, since WebExtensions have no way to focus or not focus the urlbar.  Please file a bug [over here](https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Toolbars%20and%20Customization), and hopefully it'll get fixed by one of the front-end developers.

**Closed as completed by bwinton** 2017-08-15 20:05 UTC

**Comment by strugee** [comment] 2017-08-15 20:10
Will do, thanks very much @bwinton!
