### ISSUE TITLE
Seems to be broke in FF 41

### ISSUE THREAD

**Issue by Nolski** [bwinton/whimsy#131] opened 2015-07-08 17:26 UTC
I'm running FF 41 (Developer Edition) with all other add-ons disabled whimsy no longer replaces the new tab tiles with gifs. The awesome bar text replacement still works however.

**Comment by bwinton** [comment] 2015-07-08 19:34
I can't reproduce this locally.  Can I get more details about your setup?
Operating system and full version from "About Firefox" (i.e. "40.0a2 (2015-06-29)")?
Does anything show up in the Browser Console (Ctrl-Shift-J or Cmd-Shift-J)?

**Comment by Nolski** [comment] 2015-07-08 19:42
This is running on OSX with FF 41.0a2 (2015-07-07). Looking at the browser console it looks like whimsy is throwing this error
```
TypeError: target.QueryInterface is not a function
Stack trace:
getFrameElement@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/window/utils.js:443:4
getFrame@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/input/frame.js:32:39
lift/</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/utils.js:163:28
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
receive@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/utils.js:115:5
InputPort.prototype.observe@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/input/system.js:100:5
ObserverParent.notify@resource://gre/modules/RemoteAddonsParent.jsm:347:9
ObserverParent.receiveMessage@resource://gre/modules/RemoteAddonsParent.jsm:337:9
```

I'm also noticing `unsafe CPOW usage` as a warning

**Comment by bwinton** [comment] 2015-07-08 20:07
Dangit, CPOWs!  Maybe @mikeconley or @sarracini have run into this before or know how to fix it…
(It looks like `about:nope` is the only feature that calls QueryInterface.  Do you still see the error if you toggle the “Release the Kraken!” pref?)

**Comment by mikeconley** [comment] 2015-07-08 20:11
Hey @Nolski, are you able to reproduce in a fresh profile? https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by Nolski** [comment] 2015-07-08 21:30
I rarely mess around with my profile. When I create a fresh profile, it auto launches in FF 39 instead of 41 (since I have both installed). Is there a way to launch in 41 with the fresh profile?

**Comment by bwinton** [comment] 2015-08-28 15:07
Go to `about:addons`, and click the “Preferences” button beside “Whimsy Pro”.  There should be a checkbox a little way down that page.

**Comment by bwinton** [comment] 2015-08-28 15:07
(Also, I apologize for the lateness of my reply!)

**Comment by bwinton** [comment] 2017-07-04 20:37
I'm pretty sure the upcoming switch to a WebExtension will prevent this error, so I'm going to close this issue…  😉

**Closed by bwinton** 2017-07-04 20:37 UTC
